// <auto-generated />
using System;
using FarmManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FarmManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210101040354_AddPhotoPathColumn")]
    partial class AddPhotoPathColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("FarmManagement.Models.Sapling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CultivarName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InitialPrice")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpeciesName")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Saplings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CultivarName = "Banganapalli",
                            InitialPrice = 155,
                            Name = "Banganapalli Mamidi",
                            SpeciesName = 1
                        },
                        new
                        {
                            Id = 2,
                            CultivarName = "Thai Pink Guava",
                            InitialPrice = 203,
                            Name = "Red Jama",
                            SpeciesName = 2
                        },
                        new
                        {
                            Id = 3,
                            CultivarName = "Apple Bear",
                            InitialPrice = 255,
                            Name = "Pedha Regayi",
                            SpeciesName = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
